// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtAzgj8tD-hPMPB2gTI9jmHrj1f5vDoeE',
    appId: '1:571656365710:web:2381004d1e9296432f4bdf',
    messagingSenderId: '571656365710',
    projectId: 'anonymouschat-8b968',
    authDomain: 'anonymouschat-8b968.firebaseapp.com',
    databaseURL: 'https://anonymouschat-8b968-default-rtdb.firebaseio.com',
    storageBucket: 'anonymouschat-8b968.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtE-4RK1Xk1pyAzoTHBnky0Trsu4N9J6M',
    appId: '1:571656365710:android:6f0aa0e217e839e22f4bdf',
    messagingSenderId: '571656365710',
    projectId: 'anonymouschat-8b968',
    databaseURL: 'https://anonymouschat-8b968-default-rtdb.firebaseio.com',
    storageBucket: 'anonymouschat-8b968.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfLlmFSY4cf80Nq11pRzTfVgB_jwoPd3o',
    appId: '1:571656365710:ios:e253f969590b2c222f4bdf',
    messagingSenderId: '571656365710',
    projectId: 'anonymouschat-8b968',
    databaseURL: 'https://anonymouschat-8b968-default-rtdb.firebaseio.com',
    storageBucket: 'anonymouschat-8b968.firebasestorage.app',
    iosBundleId: 'com.example.anonymousChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfLlmFSY4cf80Nq11pRzTfVgB_jwoPd3o',
    appId: '1:571656365710:ios:e253f969590b2c222f4bdf',
    messagingSenderId: '571656365710',
    projectId: 'anonymouschat-8b968',
    databaseURL: 'https://anonymouschat-8b968-default-rtdb.firebaseio.com',
    storageBucket: 'anonymouschat-8b968.firebasestorage.app',
    iosBundleId: 'com.example.anonymousChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtAzgj8tD-hPMPB2gTI9jmHrj1f5vDoeE',
    appId: '1:571656365710:web:044455991551af262f4bdf',
    messagingSenderId: '571656365710',
    projectId: 'anonymouschat-8b968',
    authDomain: 'anonymouschat-8b968.firebaseapp.com',
    databaseURL: 'https://anonymouschat-8b968-default-rtdb.firebaseio.com',
    storageBucket: 'anonymouschat-8b968.firebasestorage.app',
  );
}
